### ISSUE TITLE
视频流检测问题

### ISSUE THREAD

**Issue by javadoge** [mymagicpower/AIAS#13]
问题：使用demo测试发现涉及到视频流检测的，会报错如下：

Exception in thread "main" java.lang.ExceptionInInitializerError
	at ai.djl.paddlepaddle.engine.PpEngine.newBaseManager(PpEngine.java:110)
	at ai.djl.paddlepaddle.engine.PpEngine.newModel(PpEngine.java:92)
	at ai.djl.Model.newInstance(Model.java:98)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:187)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:149)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:132)
	at me.aias.example.RtspFaceMaskDetectionExample.faceMaskDetection(RtspFaceMaskDetectionExample.java:108)
	at me.aias.example.RtspFaceMaskDetectionExample.main(RtspFaceMaskDetectionExample.java:45)
Caused by: ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:81)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:177)
	at ai.djl.engine.Engine.getInstance(Engine.java:132)
	at ai.djl.paddlepaddle.engine.PpEngine.getAlternativeEngine(PpEngine.java:54)
	at ai.djl.ndarray.BaseNDManager.<init>(BaseNDManager.java:57)
	at ai.djl.paddlepaddle.engine.PpNDManager.<init>(PpNDManager.java:33)
	at ai.djl.paddlepaddle.engine.PpNDManager.<init>(PpNDManager.java:28)
	at ai.djl.paddlepaddle.engine.PpNDManager$SystemManager.<init>(PpNDManager.java:115)
	at ai.djl.paddlepaddle.engine.PpNDManager.<clinit>(PpNDManager.java:30)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\.djl.ai\pytorch\1.11.0-cu113-win-x86_64\cudnn_cnn_train64_8.dll: 找不到指定的程序

其他模型运行没问题，用dll工具查看此dll也没有依赖错误信息，此dll也是存在的

**Comment by henrenzhenhenrenzhenderen** [comment]
请问问题解决了吗，我也遇到了这个问题

**Comment by RingErSan** [comment]
PyTorch 和 cuda 需要相应的版本。或者把cuda文件下相应的dll文件复制到依赖文件夹。

**Comment by javadoge** [comment]
> 请问问题解决了吗，我也遇到了这个问题

版本问题
